# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name updateCorrectCoefCpp
#' @rdname updateCorrectCoefCpp
#' @title   High‐performance C++ core for update.CorrectCoef
#' @description
#'   RcppArmadillo implementation of the “a”/“b” coefficient updater used by CordBat.
#' @param X0_glist   List of G reference‐batch matrices (each n0×p).
#' @param X1_glist   List of G non‐reference batch matrices (each n1×p).
#' @param ThetaList  List of G precision (p×p) matrices.
#' @param a_i        Numeric vector length p of current “a” coefficients.
#' @param b_i        Numeric vector length p of current “b” coefficients.
#' @param penal_ksi    Numeric penalty on “a” (soft‐threshold λ for a‐update).
#' @param penal_gamma  Numeric penalty on “b” (soft‐threshold λ for b‐update).
#' @return A list with components \code{coef.a} and \code{coef.b} (each numeric length p).
#' @export
updateCorrectCoefCpp <- function(X0_glist, X1_glist, ThetaList, a_i, b_i, penal_ksi, penal_gamma) {
    .Call(`_CordBat_updateCorrectCoefCpp`, X0_glist, X1_glist, ThetaList, a_i, b_i, penal_ksi, penal_gamma)
}

